# Classification Project

## File IO

Only File IO...

You may not change this code.

In [13]:
from tkinter.filedialog import askopenfilename
import pandas as pd
import tkinter
import os

tk_window = tkinter.Tk()
cwd = os.getcwd()

tr_data = pd.read_csv(askopenfilename(title='Choose your training data'))

tr_ans = pd.read_csv(askopenfilename(title='Choose your training answer'))

tr_ans = tr_ans.iloc[:, 0]

ts_data = pd.read_csv(askopenfilename(title='Choose your test data'))

tk_window.destroy()



## Predict Algorithm

Type your source code (Champion Algorithm)

In [14]:
from sklearn.preprocessing import LabelEncoder, LabelBinarizer

le =LabelBinarizer()
tr_data['department'] = le.fit_transform(tr_data.department)
ts_data['department'] = le.fit_transform(ts_data.department)

tr_data.drop(['number_of_projects'], axis = 1, inplace =True)
ts_data.drop(['number_of_projects'], axis = 1, inplace =True)


In [32]:
import numpy as np
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore', module='sklearn')

from sklearn.preprocessing import MinMaxScaler

msc =  MinMaxScaler()

tr_data = pd.DataFrame(msc.fit_transform(tr_data),  # this is an np.array, not a dataframe.
                    columns=tr_data.columns)

ts_data = pd.DataFrame(msc.fit_transform(ts_data),  # this is an np.array, not a dataframe.
                    columns=tr_data.columns)

tr_data, ts_test, tr_ans, ts_ans = train_test_split(tr_data, tr_ans, test_size=0.2, random_state=42)

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=45, weights='distance',leaf_size=100, algorithm='ball_tree',n_jobs=-1)

knn = knn.fit(tr_data, tr_ans)

y_pred = knn.predict(ts_data)

pred_df = pd.DataFrame(y_pred)

pred_df.to_csv("output.csv", mode='w')

# End of Demo

In [5]:
import warnings
warnings.filterwarnings('ignore', module='sklearn')

from sklearn.preprocessing import MinMaxScaler

msc =  MinMaxScaler()

tr_data = pd.DataFrame(msc.fit_transform(tr_data),  # this is an np.array, not a dataframe.
                    columns=tr_data.columns)

ts_data = pd.DataFrame(msc.fit_transform(ts_data),  # this is an np.array, not a dataframe.
                    columns=tr_data.columns)


from sklearn.ensemble import ExtraTreesClassifier

EC = ExtraTreesClassifier(random_state=42, n_estimators=139)
EC = EC.fit(tr_data, tr_ans)

y_pred = EC.predict(y_test)
pred_df = pd.DataFrame(y_pred)

pred_df.to_csv("output.csv", mode='w')
# End of Demo

In [15]:
import warnings
warnings.filterwarnings('ignore', module='sklearn')

from sklearn.preprocessing import MinMaxScaler

msc =  MinMaxScaler()

tr_data = pd.DataFrame(msc.fit_transform(tr_data),  # this is an np.array, not a dataframe.
                    columns=tr_data.columns)

ts_data = pd.DataFrame(msc.fit_transform(ts_data),  # this is an np.array, not a dataframe.
                    columns=tr_data.columns)



from sklearn.neighbors import RadiusNeighborsClassifier

RNC = RadiusNeighborsClassifier(radius=2.0)
RNC = RNC.fit(tr_data, tr_ans)

y_pred = RNC.predict(ts_data)
pred_df = pd.DataFrame(y_pred)

pred_df.to_csv("output.csv", mode='w')
# End of Demo

## Check Accuracy

Only for check accuracy

In [33]:
def accuracy(real, predict):
    return sum(real == predict) / float(real.shape[0])

tk_window = tkinter.Tk()
cwd = os.getcwd()
ts_ans = pd.read_csv(askopenfilename(title='Choose your test answer'))
ts_ans = ts_ans.iloc[:, 0]
tk_window.destroy()

print(accuracy(ts_ans, y_pred))

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(accuracy(ts_ans, y_pred))
print("Confusion Matrix:\n{}\n".format(confusion_matrix(ts_ans, y_pred)))

0.48049349783261086
0.48049349783261086
Confusion Matrix:
[[  0  94 142]
 [  1 791 656]
 [  0 665 650]]



In [11]:
k_range = list(range(200,400, 1))
scores = []
for k in k_range:
    #knn = KNeighborsClassifier(n_neighbors=k)
    #knn.fit(X_train, y_train)
    #y_pred = knn.predict(X_test)
    EC = ExtraTreesClassifier(random_state=42, n_estimators=k, max_features=3)
    EC = EC.fit(tr_data, tr_ans)
    y_pred = EC.predict(ts_data)
    pred_df = pd.DataFrame(y_pred)

    scores.append(accuracy(ts_ans, y_pred))
    print(accuracy(ts_ans, y_pred), k)
   #15,8,7
    #k=3, 138, 213

0.5070833333333333 200
0.5078333333333334 201
0.5071666666666667 202
0.5078333333333334 203
0.5081666666666667 204
0.5075833333333334 205
0.5079166666666667 206
0.5075 207
0.5074166666666666 208
0.508 209
0.50825 210
0.5075833333333334 211
0.507 212
0.5075833333333334 213
0.5080833333333333 214
0.5088333333333334 215
0.5078333333333334 216
0.5076666666666667 217
0.5075833333333334 218
0.50775 219
0.508 220
0.50775 221
0.5079166666666667 222
0.5075833333333334 223
0.5083333333333333 224
0.5089166666666667 225
0.5074166666666666 226
0.508 227
0.5075 228
0.508 229
0.5074166666666666 230
0.508 231
0.5078333333333334 232
0.50775 233
0.50825 234
0.5080833333333333 235
0.508 236
0.5089166666666667 237
0.5083333333333333 238
0.5085833333333334 239
0.5086666666666667 240
0.5081666666666667 241
0.508 242
0.5073333333333333 243
0.508 244
0.5069166666666667 245
0.5075 246
0.5063333333333333 247
0.5065833333333334 248
0.5069166666666667 249
0.5063333333333333 250
0.5060833333333333 251
0.507 252
0.